version: '3.4 '
services:
  my-todo-app:
    container_name: dc-my-todo-app
    build: .
    ports:
      - 3001:3000
  mongodb:
    container_name: dc-mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dc-my-todo-app-data:/data/db # datanin kaybolmamasi icin
volumes:
  dc-my-todo-app-data:
